version: "3.8"

name: snippetbox

services:
  back:
    build:
      dockerfile: docker/go/Dockerfile
      context: .
    volumes:
      - ./cmd/:/app/cmd
      - ./internal/:/app/internal
      - ./ui/:/app/ui
    ports:
      - "4000:4000"
    command: air
  mysql:
    image: mysql
    volumes:
      - snippetbox-mysql-data:/var/lib/mysql
      - ./init.sql:/data/application/init.sql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: snippetboxadmin
      MYSQL_DATABASE: snippetbox
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --init-file /data/application/init.sql

volumes:
  snippetbox-mysql-data:
