version: "3.8"

name: snippetbox

services:
  mysql:
    image: mysql
    volumes:
      - snippetbox-mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: web
      MYSQL_PASSWORD: webpass
      MYSQL_ROOT_PASSWORD: snippetboxadmin
      MYSQL_DATABASE: snippetbox
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

volumes:
  snippetbox-mysql-data:
